tap "felixkratz/formulae", trusted: true
tap "fsouza/prettierd", trusted: true
tap "jandedobbeleer/oh-my-posh", trusted: true
tap "joncrangle/tap", trusted: true
tap "koekeishiya/formulae", trusted: true
tap "mhaeuser/mhaeuser", trusted: true
tap "nikitabobko/tap", trusted: true
brew "bat"
brew "blueutil"
brew "btop"
brew "cask"
brew "eza"
brew "fd"
brew "flux"
brew "fzf"
brew "git"
brew "git-delta"
brew "jq"
brew "neovim"
brew "node"
brew "nowplaying-cli"
brew "python@3.14"
brew "pipx"
brew "ripgrep"
brew "sleepwatcher", restart_service: :changed
brew "starship"
brew "stow"
brew "task"
brew "taskwarrior-tui"
brew "tldr"
brew "tmux"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "zsh-vi-mode"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "fsouza/prettierd/prettierd"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "joncrangle/tap/sketchybar-system-stats"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "nikitabobko/tap/aerospace"
cask "brave-browser"
cask "ente-auth"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "hammerspoon"
cask "kitty"
cask "librewolf"
cask "maccy"
cask "obsidian"
cask "pearcleaner"
cask "proton-drive"
cask "raycast"
cask "spotify"
cask "stolendata-mpv"
cask "stremio"
cask "tuta-mail"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
