# ============================================
# ESSENTIAL SETTINGS
# ============================================
# fix vim escape delay
set -sg escape-time 0

# enable focus events for vim autoread
set -g focus-events on

# increase scrollback buffer
set -g history-limit 50000

# mouse support
set -g mouse on

# start index at 1
set -g base-index 1
set -g pane-base-index 1

# enhance colors
# set -g default-terminal "tmux-256color"
# set -as terminal-features ",xterm-256color:RGB"

# disable auto-rename
set -g automatic-rename off
set -g allow-rename off


# ============================================
# KEY BINDINGS
# ============================================
# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# pane splitting (keep current path)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# ============================================
# APPEARANCE
# ============================================

# Status bar
set-option -g status-position top
set -g status-style "bg=#181825,fg=#cdd6f4"

# Pane border separator line
set -g pane-border-status top
set -g pane-border-format ""
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#313244"

# Command line

# set -g message-style "bg=#f38ba8,fg=#1e1e2e"
#
# # Maroon — darker muted red
# set -g message-style "bg=#7f3b4e,fg=#cdd6f4"
#
# # Surface with red text instead
# set -g message-style "bg=#313244,fg=#f38ba8"

# Flamingo — softer pinkish red
set -g message-style "bg=#f2cdcd,fg=#1e1e2e"

# positions
set -g status-justify absolute-centre
# set -g status-right ""
set -g status-left ""
set -g status-right "#S"
# ============================================
# COPY MODE
# ============================================
setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"


# ============================================
# PLUGINS
# ============================================
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
#
# run '~/.tmux/plugins/tpm/tpm'
