# Catppuccin-Mocha
include theme.conf

#font
# font_family      SF Mono
# bold_font        SF Mono Bold
# italic_font      SF Mono Light Italic
# bold_italic_font SF Mono Heavy Italic
# font_family      JetBrainsMono Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 16

#window
window_padding_width 2 5
placement_strategy center

#background
background_opacity 0.95
background_blur 20

#cursor
# shell_integration no-cursor
# cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0


#cancel using cmd+c in mac
# map cmd+c send_text all \x03

